apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: apps
spec:
  chart:
    spec:
      chart: homarr
      sourceRef:
        kind: HelmRepository
        name: oben01
        namespace: apps
      version: 1.2.5
  interval: 1h
  values:
    env:
      AUTH_OIDC_ADMIN_GROUP: "authentik Admins"
      AUTH_PROVIDER: oidc
      AUTH_OIDC_URI: https://auth.homelab.haseebmajid.dev/application/o/homarr
      AUTH_OIDC_CLIENT_NAME: authentik
      AUTH_OIDC_AUTO_LOGIN: true
      BASE_URL: homarr.homelab.haseebmajid.dev
      NEXTAUTH_URL: https://homarr.homelab.haseebmajid.dev
    envSecrets:
      AUTH_OIDC_CLIENT_ID:
       name: homarr-oauth
       key: client-id
      AUTH_OIDC_CLIENT_SECRET:
        name: homarr-oauth
        key: client-secret
    persistence:
      - name: homarr-config
        enabled: true
        storageClassName: "longhorn"
        accessMode: "ReadWriteOnce"
        size: "50Mi"
        mountPath: "/app/data/configs"
      - name: homarr-database
        enabled: true
        storageClassName: "longhorn"
        accessMode: "ReadWriteOnce"
        size: "50Mi"
        mountPath: "/app/database"
      - name: homarr-icons
        enabled: true
        storageClassName: "longhorn"
        accessMode: "ReadWriteOnce"
        size: "50Mi"
        mountPath: "/app/public/icons"
    ingress:
      enabled: true
      className: traefik
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: homarr.homelab.haseebmajid.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - homarr.homelab.haseebmajid.dev
          secretName: homarr-haseebmajid-dev-tls


