apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: prod
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:q2Bxg7nR6rmCWaU7Exluj5MxCamfmPjN3YTmjVhCTsQiWGjnrmrugqd+qacNN0v89hXU4NtVYXwSR7UsNkRC630LXzZRtaF3lhCBnSVKnxBG5TvIw3wrgBUegkItjZthqL1qdQFUDrAioEbP6lI+eBihNBMEC/ZYtIkgtCKqheHsnRPP3FfktTxLZ/Vky8o9DfQ+mJSS4y26j58LwU0WqFY=,iv:9sKbj1rRNA7b+08Kpe/mBpmSVgromvaz2j3c3XkSOt0=,tag:gROPXuLGqTT8nvPgLL+MiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ham2fhsrkrjhstzwxxzmuqxeql86wm75lul6cu2xe4zwew5zg3vq3mfvm5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITTVEdmREdzkrSmRnODNJ
            WXh2MnNMaVFVUkdJNHQwNFY0aXo4d1E3aTJFCjNOSUdFTFFwT3ZjdjBzVXlBYUJR
            MnVFRGlYRnR0amVjcG1sYkZhSDFUdGcKLS0tIGRKaGxhNFdqSlZnKzBjaGJrcGtO
            QkUwc2x0dmh6ZXRQZzFCYko2VHFtNmcKMGXFeXOvh2NiLl5tuO3nxIY07zLlZTe9
            26IHdJepS35SC8/dMpzET2m7HE5ApxCnZ0SktzP6bZViwYrH1Nej1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T22:47:37Z"
    mac: ENC[AES256_GCM,data:PKb+a6GK+woDz4X/7I0syl/4KyBg3NDAnU4OfYNLuxTZOj8aZfQOmNFTh9vNGJIrDp+Him86EQ61JcxYt68A6b923scqAJdIBDIBwRjRia6WiHBm25wtyuFUew3jAK0ARAdhYhD19wOablA7YW8dhD2IFuZ9HagSXA1o7c3Rf6A=,iv:+bkT2EZ94nBKsQn8h4bkoUFoLGYPs6JstuAFSfhUKOg=,tag:0SyyARFngEr/lmcfVENqhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
