apiVersion: v1
kind: Service
metadata:
  name: tempo2
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/name: tempo
  ports:
    - name: tempo-prom-metrics
      port: 3100
      targetPort: 3100
      nodePort: 31100
