apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: "1.16.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    storage:
      trace:
        backend: s3
        s3:
          access_key:
            valueFrom:
              secretKeyRef:
                name: tempo
                key: access_key
          secret_key:
            valueFrom:
              secretKeyRef:
                name: tempo
                key: secret_key
        bucket: 'tempo'
        endpoint: 'minio.homelab.haseebmajid.dev'
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: false
      jaeger:
        thriftHttp:
          enabled: false
      opencensus:
        enabled: false
