apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: "1.16.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    persistence:
      enabled: true
    #   size: 10Gi
    #   storageClassName: "standard"  # Adjust this to match your cluster's storage class
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: false
      jaeger:
        thriftHttp:
          enabled: false
      opencensus:
        enabled: false
