apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timetagger
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
