resources:
  - ../../base/banterbus
  - ./secrets.yaml
configMapGenerator:
  - name: banterbus
    literals:
      - BANTERBUS_DB_USERNAME=banterbus
      - BANTERBUS_DB_NAME=banterbus
      - BANTERBUS_ENVIRONMENT=production
namespace: prod
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-prod:name"}
    newTag: prod-a9a52d3eb74c8937cdb94b27668c6242974352c2-1736720679 # {"$imagepolicy": "flux-system:banterbus-prod:tag"}
patchesStrategicMerge:
  - deployment-patch.yaml
