resources:
  - ../../base/banterbus
  - ./secrets.yaml
configMapGenerator:
  - name: banterbus
    literals:
      - BANTERBUS_DB_USERNAME=banterbus
      - BANTERBUS_DB_NAME=banterbus
      - BANTERBUS_ENVIRONMENT=production
namespace: prod
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-prod:name"}
    newTag: prod-b9f87b7a7bd352590310ee03f8c952947116bcd7-1737914363 # {"$imagepolicy": "flux-system:banterbus-prod:tag"}
patchesStrategicMerge:
  - deployment-patch.yaml
