resources:
  - ../../base/banterbus
  - ./secrets.yaml
configMapGenerator:
  - name: banterbus
    literals:
      - BANTERBUS_DB_USERNAME=banterbus
      - BANTERBUS_DB_NAME=banterbus
      - BANTERBUS_ENVIRONMENT=production
namespace: prod
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-prod:name"}
    newTag: prod-baf63204784b3e491bab9af30e26e81ec47d6cc8-1738677613 # {"$imagepolicy": "flux-system:banterbus-prod:tag"}
patchesStrategicMerge:
  - deployment-patch.yaml
