resources:
  - ../../base/banterbus
  - ./secrets.yaml
  - ./configmap.yaml
# configMapGenerator:
# - name: banterbus
#   behavior: merge
#   files:
#   - ./configmap.yaml
namespace: prod
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-prod:name"}
    newTag: prod-1ed5e001dfe0ec8944744f98fe3c6e74458296e3-1736624348 # {"$imagepolicy": "flux-system:banterbus-prod:tag"}
