resources:
  - ../../base/banterbus
  - ./secrets.yaml
configMapGenerator:
  - name: banterbus
    literals:
      - BANTERBUS_DB_USERNAME=banterbus
      - BANTERBUS_DB_NAME=banterbus
      - BANTERBUS_ENVIRONMENT=production
namespace: prod
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-prod:name"}
    newTag: prod-16bf5752eb9deb4b9129d4c139d5a518a4ca1eee-1739222466 # {"$imagepolicy": "flux-system:banterbus-prod:tag"}
patchesStrategicMerge:
  - deployment-patch.yaml
