resources:
  - ../../base/banterbus
  - ./secrets.yaml
configMapGenerator:
  - name: banterbus
    literals:
      - BANTERBUS_DB_USERNAME=banterbus
      - BANTERBUS_DB_NAME=banterbus
      - BANTERBUS_ENVIRONMENT=production
namespace: prod
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-prod:name"}
    newTag: prod-1a5e3c26128e056dfc94de0c683e60314322da18-1736876988 # {"$imagepolicy": "flux-system:banterbus-prod:tag"}
patchesStrategicMerge:
  - deployment-patch.yaml
