resources:
  - ../../base/banterbus
  - ./secrets.yaml
configMapGenerator:
  - name: banterbus
    literals:
      - BANTERBUS_DB_USERNAME=banterbus_dev
      - BANTERBUS_DB_NAME=banterbus_dev
      - BANTERBUS_ENVIRONMENT=development
namespace: dev
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-dev:name"}
    newTag: dev-bc4dd2504a320bd3fe4a5cac62c97a65426459ea-1737926166 # {"$imagepolicy": "flux-system:banterbus-dev:tag"}
patchesStrategicMerge:
  - deployment-patch.yaml
