resources:
  - ../../base/banterbus
  - ./secrets.yaml
  - ./configmap.yaml
# configMapGenerator:
# - name: banterbus
#   behavior: merge
#   files:
#   - ./configmap.yaml
namespace: dev
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-dev:name"}
    newTag: dev-4b679cc33f5e7611bcdd26f7edd70e5d38afb572-1736189058 # {"$imagepolicy": "flux-system:banterbus-dev:tag"}
