resources:
  - ../../base/banterbus
  - ./secrets.yaml
configMapGenerator:
  - name: banterbus
    literals:
      - BANTERBUS_DB_USERNAME=banterbus_dev
      - BANTERBUS_DB_NAME=banterbus_dev
      - BANTERBUS_ENVIRONMENT=development
namespace: dev
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-dev:name"}
    newTag: dev-b6fbb6e91db26fa4fc6a55e77ead8a103ce4dfe4-1736895008 # {"$imagepolicy": "flux-system:banterbus-dev:tag"}
patchesStrategicMerge:
  - deployment-patch.yaml
