resources:
  - ../../base/banterbus
  - ./secrets.yaml
configMapGenerator:
  - name: banterbus
    literals:
      - BANTERBUS_DB_USERNAME=banterbus_dev
      - BANTERBUS_DB_NAME=banterbus_dev
      - BANTERBUS_ENVIRONMENT=development
namespace: dev
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-dev:name"}
    newTag: dev-5ace91533e0eb01c0280f86f27161d24db12a60b-1737912577 # {"$imagepolicy": "flux-system:banterbus-dev:tag"}
patchesStrategicMerge:
  - deployment-patch.yaml
