resources:
  - ../../base/banterbus
  - ./secrets.yaml
  - ./configmap.yaml
# configMapGenerator:
# - name: banterbus
#   behavior: merge
#   files:
#   - ./configmap.yaml
namespace: dev
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-dev:name"}
    newTag: dev-ebf586cda4405638888f27bef08ee8ce96db40bb-1736599518 # {"$imagepolicy": "flux-system:banterbus-dev:tag"}
