resources:
  - ../../base/banterbus
  - ./secrets.yaml
configMapGenerator:
  - name: banterbus
    literals:
      - BANTERBUS_DB_USERNAME=banterbus_dev
      - BANTERBUS_DB_NAME=banterbus_dev
      - BANTERBUS_ENVIRONMENT=development
namespace: dev
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-dev:name"}
    newTag: dev-71d432a7e54b407b87c70b67536303f9d1e70056-1748851584 # {"$imagepolicy": "flux-system:banterbus-dev:tag"}
patchesStrategicMerge:
  - deployment-patch.yaml
