resources:
  - ../../base/banterbus
  - ./secrets.yaml
configMapGenerator:
  - name: banterbus
    literals:
      - BANTERBUS_DB_USERNAME=banterbus_dev
      - BANTERBUS_DB_NAME=banterbus_dev
      - BANTERBUS_ENVIRONMENT=development
namespace: dev
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-dev:name"}
    newTag: dev-7fe9e9f03b438bbfd6ed13a4f4222f4b34db780a-1736715694 # {"$imagepolicy": "flux-system:banterbus-dev:tag"}
patchesStrategicMerge:
  - deployment-patch.yaml
