resources:
  - ../../base/banterbus
  - ./secrets.yaml
  - ./configmap.yaml
# configMapGenerator:
# - name: banterbus
#   behavior: merge
#   files:
#   - ./configmap.yaml
namespace: dev
images:
  - name: registry.gitlab.com/hmajid2301/banterbus
    newName: registry.gitlab.com/hmajid2301/banterbus # {"$imagepolicy": "flux-system:banterbus-dev:name"}
    newTag: dev-ddbbd15c3d2935c802d371830456c4dcb2a9a050-1736372688 # {"$imagepolicy": "flux-system:banterbus-dev:tag"}
