apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-prometheus2
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http-web
      port: 9090
      targetPort: 9090
      nodePort: 30906
    - name: reloader-web
      port: 8080
      targetPort: 8080
      nodePort: 30907
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: kube-prometheus-stack-prometheus
