apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.111.1"
      sourceRef:
        kind: HelmRepository
        name: otel
        namespace: monitoring
      interval: 12h
  values:
    mode: deployment

    image:
      repository: "otel/opentelemetry-collector-contrib"

    ports:
      metrics:
        enabled: true
        containerPort: 8889
        servicePort: 8889
        protocol: TCP

    podMonitor:
      enabled: true

    serviceMonitor:
      enabled: true

    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

      processors:
        batch: {}

      exporters:
        otlp:
          endpoint: "tempo.monitoring.svc.cluster.local:4317"
          tls:
            insecure: true
        prometheus:
          endpoint: ${env:MY_POD_IP}:8889

      service:
        pipelines:
          traces:
            receivers: ["otlp"]
            processors: ["batch"]
            exporters: ["otlp"]
          metrics:
            receivers: ["otlp"]
            processors: ["batch"]
            exporters: ["prometheus"]
