apiVersion: apps/v1
kind: Deployment
metadata:
  name: banterbus
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banterbus
  template:
    metadata:
      labels:
        app: banterbus
    spec:
      restartPolicy: Always
      containers:
        - name: banterbus
          image: registry.gitlab.com/banterbus/banterbus:prod-908a2a9ed714244d255aef0bc1f262f1f17b8c60-1755863414
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          env:
            - name: BANTERBUS_REDIS_ADDRESS
              value: redis.homelab.haseebmajid.dev:6381
            - name: BANTERBUS_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: banterbus
                  key: BANTERBUS_DB_USERNAME
            - name: BANTERBUS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: banterbus
                  key: BANTERBUS_DB_NAME
            - name: BANTERBUS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banterbus
                  key: db_password
            - name: BANTERBUS_DB_HOST
              value: postgres.homelab.haseebmajid.dev
            - name: BANTERBUS_DB_PORT
              value: "5433"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318
            - name: BANTERBUS_JWKS_URL
              value: https://authentik.haseebmajid.dev/application/o/budibase/jwks/
            - name: BANTERBUS_JWT_ADMIN_GROUP
              value: "authentik Admins"
