apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: banterbus-dev
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: banterbus
  filterTags:
    pattern: '^dev-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: banterbus-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: banterbus
  filterTags:
    pattern: '^prod-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
