apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: banterbus
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      release: kube-prometheus-stack
  endpoints:
  - port: "8080"
    path: /metrics
