apiVersion: v1
kind: Service
metadata:
  name: loki-gateway2
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http-metrics
      port: 80
      targetPort: 8080
      nodePort: 31111
  selector:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
