apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: budibase
  namespace: apps
spec:
  chart:
    spec:
      chart: budibase
      sourceRef:
        kind: HelmRepository
        name: budibase
        namespace: apps
      version: "*"
  interval: 1h
  values:
    services:
      objectStore:
        minio: false
        url: "https://minio.homelab.haseebmajid.dev"
        accessKey:
          valueFrom:
            secretKeyRef:
              name: budibase
              key: minio_access_key
        secretKey:
          valueFrom:
            secretKeyRef:
              name: budibase
              key: minio_secret_key

      # redis:
      #    enabled: false
      #    url: "redis.homelab.haseebmajid.dev:6381"

      couchdb:
         enabled: false
         url: "https://couchdb.homelab.haseebmajid.dev"
         user: "budibase"
           # valueFrom:
           #   secretKeyRef:
           #     name: budibase
           #     key: couchdb_user
         password:
           valueFrom:
             secretKeyRef:
               name: budibase
               key: couchdb_pass
