apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: budibase
  namespace: apps
spec:
  chart:
    spec:
      chart: budibase
      sourceRef:
        kind: HelmRepository
        name: budibase
        namespace: apps
      version: "*"
  interval: 1h
  values:
