apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: budibase
  namespace: apps
spec:
  chart:
    spec:
      chart: budibase
      sourceRef:
        kind: HelmRepository
        name: budibase
        namespace: apps
      version: "*"
  interval: 1h
  values:
    ingress:
      enabled: true
      className: "traefik"
      hosts:
        - host: "budibase.k8s.homelab.haseebmajid.dev"
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: proxy-service
                  port:
                    number: 10000
